import express from "express";
import path from "path";
import { GoogleGenAI } from "@google/genai";

// Lazy-loaded Gemini client
let aiInstance: GoogleGenAI | null = null;

function getGenAI(): GoogleGenAI {
  if (!aiInstance) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === "MY_GEMINI_API_KEY" || apiKey.trim() === "") {
      throw new Error("GEMINI_API_KEY environment variable is missing. Please configure it in Settings > Secrets.");
    }
    aiInstance = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiInstance;
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Configure high body limit for base64 image uploads
  app.use(express.json({ limit: "15mb" }));

  // API Endpoint: Health check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", apiKeyConfigured: !!process.env.GEMINI_API_KEY });
  });

  // API Endpoint: /analyze
  app.post("/api/analyze", async (req, res) => {
    try {
      const { image, mimeType } = req.body;

      if (!image) {
        return res.status(400).json({ error: "Missing uploaded image data." });
      }

      const ai = getGenAI();

      const imagePart = {
        inlineData: {
          mimeType: mimeType || "image/png",
          data: image,
        },
      };

      const systemInstruction = `You are a medical educational assistant.
Analyze the uploaded image carefully.

Rules:
* Never claim certainty.
* State that analysis is based only on visible information.
* Do not provide diagnosis.
* Mention uncertainty.
* If image quality is poor or if it doesn't represent a visible health concern (e.g. random objects, faces with no issues, landscapes), ask for a clearer or correct image (populate 'possible_condition' explaining this).
* Recommend medical evaluation for serious symptoms.

Return JSON only. Keep lists concise and descriptions accurate but understandable for a layperson.
'urgency_level' must be strictly one of: 'Green' (monitor), 'Yellow' (schedule consultation), or 'Red' (seek urgent medical attention).

Format your output exactly as this JSON schema:
{
  "possible_condition": "A likely visible health concern, or general description",
  "confidence": "Low" | "Medium" | "High",
  "what_it_might_be": "A professional but clear description of what this visible sign represents.",
  "possible_causes": [
    "Cause one description",
    "Cause two description"
  ],
  "common_signs": [
    "Sign or symptom one",
    "Sign or symptom two"
  ],
  "next_steps": [
    "General self-care step",
    "Information on when to consult a practitioner"
  ],
  "urgency_level": "Green" | "Yellow" | "Red",
  "medical_attention": "Critical instructions about when this requires physician or emergency care.",
  "disclaimer": "This analysis is for educational purposes only. AI detector results can be mistaken. Always consult a qualified physician.",
  "spoken_summary": "Based on the image details, this resembles a visible health concern. Possible causes are often mild, but can vary. Please monitor symptoms and schedule a professional consultation if you notice any spreading, infection, or pain."
}`;

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: [
          imagePart,
          { text: "Analyze the uploaded photograph of a visible concern and provide structured educational insight." }
        ],
        config: {
          systemInstruction: systemInstruction,
          responseMimeType: "application/json",
          temperature: 0.2, // low temperature for consistent schema-guided generation
        },
      });

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No response content generated by Gemini.");
      }

      // Parse and forward JSON
      const parsedData = JSON.parse(responseText.trim());
      res.json({ success: true, data: parsedData });

    } catch (error: any) {
      console.error("Analysis Error:", error);
      res.status(500).json({ 
        success: false, 
        error: error.message || "An internal error occurred during the analysis." 
      });
    }
  });

  // API Endpoint: /api/tts (Text-to-Speech)
  app.post("/api/tts", async (req, res) => {
    try {
      const { text, voice } = req.body;
      if (!text) {
        return res.status(400).json({ error: "Missing text for voice generation." });
      }

      const ai = getGenAI();

      // Request text-to-speech conversion from Gemini
      const response = await ai.models.generateContent({
        model: "gemini-3.1-flash-tts-preview",
        contents: [{ parts: [{ text: text }] }],
        config: {
          responseModalities: ["AUDIO"],
          speechConfig: {
            voiceConfig: {
              // Prebuilt voices include 'Puck', 'Charon', 'Kore', 'Fenrir', 'Zephyr'
              prebuiltVoiceConfig: { voiceName: voice || "Kore" },
            },
          },
        },
      });

      const part = response.candidates?.[0]?.content?.parts?.[0];
      const audioData = part?.inlineData?.data;

      if (!audioData) {
        throw new Error("Failed to generate voice model output.");
      }

      res.json({ success: true, audio: audioData });
    } catch (error: any) {
      console.error("TTS Generation Error:", error);
      res.status(500).json({ 
        success: false, 
        error: error.message || "Speech synthesis engine could not generate native audio." 
      });
    }
  });

  // Serve static files in production / Vite middleware in dev
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Disease Detector AI server running on http://localhost:${PORT}`);
  });
}

startServer();
